# Introducción

## Motivación

Durante el último tiempo, hemos observado un creciente interés por conversar y debatir sobre los cambios y eventos que ha experimentado la participación electoral en Chile. Los cambios en la participación, la nuevas agrupaciones y conglomerados que establecen nuevos escenarios electorales y la composición y posible predición de los electores se han vuelto temas de alta relevancia a nivel nacional, por lo que cada vez existe un mayor interés en encontrar mecanismos para poder conocer mejor su funcionamiento.

En este contexto, nos hemos propuesto presentar información a través de diversas formas de visualización con el fin de poder aportar y mejorar la discusión y debate en torno a estos temas. A través de la visualización y presentación de nuevas formas de análisis buscamos establecer alternativas que puedan fomentar el desarrollo de propuestas y otras formas de discusión del fenómeno electoral. 

A través de la manipulación de datos y evidencia buscamos enriquecer la discusión pública entregando información que pueda ser interpretada de manera sencilla que fomente la discusión basada en evidencia empírica. 

Para lograr este objetivo hemos establecido dos aspectos que consideramos relevantes: 

Por un lado, la utilización de **metodología basada en evidencia**, estableciendo rigurisidad en la elaboración de información. Por lo que nuestros análisis e interpretaciones estarán enfocadas en la interpretación considerando los posibles beneficios y problemas que pueden generarse a través de la decisión de técnicas y mecanismos de interpretación de datos.

Por otro lado, para la elaboración de un adecuada evaluación e interpretación de datos, creemos que es necesario poder establecer **transparencia** del proceso a través de la presentación en conjunto de los resultados, información acerca del proceso de análisis, referencias utilizadas y explicaciones del proceso de tal modo que se pueda comprender el desarrollo y el procedimiento que lleva a cada una de estas conclusiones.


## Objetivos

En esta ocasión, nuestro objetivo contrastar la participación electoral de los votantes en cada conglomerado político. Las elecciones primarias del año 2017 y 2021 se han presentado como un escenario ideal para comparar la participación electoral en torno a dos ofertas electorales similares (pese a que han ambos han sufrido importantes cambios durante el últimpo tiempo). 

Si bien no es posible obtener inferencias o explicaciones causales que podrían explicar la preferencia de los votantes, la visualización de los cambios de tendencias pueden presentar una oportunidad única de discusión sobre los escenarios políticos que está enfrentando el país y la evaluación de aspectos contextuales que pueden afectar el desarrollo de cada uno de estos procesos.

### Metodología

Para poder evaluar las posibles diferencias en las preferencias electorales, lo primero que obtuvimos fue la información electoral de ambos comicios de la página oficial del servicio electoral. Una vez obetenidos nos tuvimos que enfrentar a los siguientes escenarios.


#### Definición de *Izquierda* y *Derecha*

Con el fin de poder distinguir si existen alguna fluctuación en las tendencias políticas de los votantes, nuestro primer desafío consistió en la elaboración de criterio para poder separar las preferencias políticas de los votantes a partir de sus sufragios. Para esto utilizaremos como supuesto que el voto implicará una preferencia por una opción política. Esta no necesarimente implicará que sea una tendencia permanente, sino al contrario, es la opción que una persona optó dado el contexto electoral de ese momento.

Considerando lo anterior, estableceremos distinguiremos las preferencias del Frente Amplio y Apruebo Dignidad quedarán agrupadas bajo la categoría "izquierda" mientras que las opciones de Chile Vamos y Chile Podemos Más como "derecha". Esta decisión no se encuentra exenta de problemas, ya que es un supuesto grande considerando que algunas alternativas pueden ser catalogadas fuera de esta dicotomía. Sin embargo,

¿Debemos ser tan *Blanco y Negro*? Por el momento sí, ya que facilita los análisis. 

¿Cuál es el beneficio de utilizar una diferencia tan arbitraria? Al ser una categorización sencilla, nos permite poder mantenerla de manera consistente en el tiempo. De la misma forma, esta separación nos permite establecer en grandes rasgos diferencias en las preferencias de votación, permitiendo identificar si sector electoral mantiene su tendencia historíca o el escenario político implicó una mayor participación en otra dirección.

Es importante clarificar que esta clasificación tienen un interés investigativo, por lo que en esta ocasión no consideraremos otros aspectos relevantes relacionadas a las diferencias políticas dentro de los conglomerados.


#### El problema de la consistencia de cada mesa y su agrupamiento

Una vez establecida las clasificaciones de los votos, nuestro siguiente elemento a considerar es las comparación de ambas elecciones. Que más quisiera un analista que tener cada mesa de manera individualizada, ubicada en el mismo lugar y ver en el tiempo como varían, pero no es tan fácil. Dependiendo de las elecciones, las mesas se agrupan y una mesa *"física"*, puede estar compuesta de varias mesas "*teóricas*". Por ejemplo, para una elección en particular, la mesa `M31` puede estar compuesta de las mesas `M31`, `M32` y `M41`. En la siguiente elección puede estar cada mesa individualizada, o agrupadas con otras mesas, por lo que no es posible llegar y comparar directamente.

Las razones para fusionar o dividir que hay detrás de la agrupación de mesas del SERVEL la desconocemos, por lo que tampoco podemos conocer con anterioridad si estos criterios se mantendrán o cambiarán en una futura elección. Junto a lo anterior, hay que considerar que también se agregan nuevas mesas al sistema, y cuando se compara en el tiempo, a veces nos quedamos sin la referencia anterior.

El escenario descrito anteriormente, nos plantea un desafío interesante ya que esta situación nos conllevará a tener que establecer un clasificación de mesas que nos permita establecer un escenario común en ambos tiempos. Para poder resolver este escenario hemos definido una agrupación de mesas como **Mesa Estacionas (ME)** las cuáles consisten en una agrupación de meses que contemplan un subconjunto de mesas que se encuentren  una agrupación de mesas que contempla una combinació n de todas las mesas que fueron combinadas entre el periodo 2017 y 2021, generando de esta forma una mesa que integra todas las posibles combinaciones, permitiendo comparar el comportamiento de todas a nivel general de estas mesas en ambos momentos. 

|Mesa 2017|Mesa 2021| ME|
|:--:|:--:|:--:|
|1-2|1|-|
|-|-|1-2-3-4|
|3|2-3-4|-|
|4|-|-|

A modo de ejemplo, tal cómo se presenta en la tabla anterior tenemos un esquema de agrupación hipotética de las mesas del año 2017 y el año 2021. Como es posible ver en el año 2017 las mesas 1-2 fueron fusionadas, mientras que en el año 2021 la mesa 1 se mantuvo separada y la mesa 2 fue fusionada con la mesa 3 y 4. En este sentido, no es posible establecer ninguna comparación de manera aislada de la mesa 1 ya que en un año se mantuvo de manera independiente, pero en otro año esta se mantuvo unida a otra mesa por lo que sus resultados no son posibles de separar. Por la misma razón la **Mesa Estacionaria** conformada por las mesas 1,2,3 y 4 permitirá hacer una comparación contemplando todas las mesas y sus relaciones de forma de poder comparar un similar número de electores en ambos eventos.


### Gráficas

A través de una recodificación política hemos clasificado en dos alternativas de participación (Eje Izquierda-Derecha) el comportamiento de cada mesa, adquiriendo un color azul en caso de obtener una mayor proporción de votos la coalición de derecha y rojo en el caso de la izquierda.

#### Nube de puntos

#### ADN

A través de este gráfico se visualiza de manera general cada uno de los vocales de votación que se encuentran en cada una de las comunas del país. Cada cuadrado corresponde a una mesa electoral - que a su vez se encuentran conformadas por las mesas fusionadas en cada elección -, en donde se le asigna un color según la característica presentada.

#### Lollipop

En contraste a los gráficos presentados anteriormente, a continuación presentaremos otros gráficos más enfocados en la presentación de información a nivel agregado con el fin de contrastar y comparar los resultados electorales a nivel comunal y regional.


Por lo mismo a través de este gráfico pretendemos presentar algunas comunas de interés y un indicador para observar su variación o tendencia en relación a una elección u otra. 



#### Otras consideraciones


1. Comparar eventos similares: se privilegio el comparar eventos de similares características, como primarias con otras primarias, parlamentarias y presidenciales entre sí. Especialmente en el caso de las primarias, la participación es normalmente baja comparada con otro tipo de elecciones, por lo que se debe tener especial cuidado cuando se realizan cruces entre este tipo de información



::: {.infobox .caution data-latex="{caution}"}
Este artículo fue redactado el 2021-11-20 y su última modificación fue en `r Sys.Date()`.
:::